import type { DepreciationCategory } from "./types";

// Tabela COMPLETA das Taxas de Reintegrações e Amortizações
// Decreto Presidencial n.º 207/15, de 5 de Novembro (Anexo)

// PGC Angola — Classe 4 (Imobilizações)
const PGC = {
  terra: "421 — Terrenos e Recursos Naturais",
  edif: "422 — Edifícios e Outras Construções",
  basico: "423 — Equipamento Básico",
  trans: "424 — Equipamento de Transporte",
  ferr: "425 — Ferramentas e Utensílios",
  adm: "426 — Equipamento Administrativo",
  outr: "429 — Outras Imobilizações Corpóreas",
  incorp: "431 — Imobilizações Incorpóreas",
} as const;

type AccKey = keyof typeof PGC;

// Helper para construir cada linha (vida útil = arredondamento de 100/taxa).
function c(
  id: string,
  group: string,
  section: string,
  description: string,
  ratePct: number,
  acc: AccKey,
  nature: "corporeo" | "incorporeo" = "corporeo",
): DepreciationCategory {
  return {
    id,
    nature,
    group,
    section,
    description,
    ratePct,
    usefulLifeYears: Math.max(1, Math.round(100 / ratePct)),
    pgcAccount: PGC[acc],
  };
}

// === Grupos (cabeçalhos do Anexo) ===
const A = "A — Agricultura, pecuária, silvicultura, aquicultura, avicultura e pesca";
const B = "B — Pesca";
const C = "C — Indústrias extractivas (excepto petrolífera e mineira)";
const DA = "D — Indústrias transformadoras — DA — Alimentares, bebidas e tabaco";
const DB = "D — Indústrias transformadoras — DB — Têxtil";
const DC = "D — Indústrias transformadoras — DC — Couro e produtos de couro";
const DD = "D — Indústrias transformadoras — DD — Madeira, cortiça e suas obras";
const DE = "D — Indústrias transformadoras — DE — Pasta de papel, papel, cartão, edição e impressão";
const DF = "D — Indústrias transformadoras — DF — Coque e produtos petrolíferos refinados";
const DG = "D — Indústrias transformadoras — DG — Produtos químicos e fibras sintéticas";
const DH = "D — Indústrias transformadoras — DH — Borracha e matérias plásticas";
const DI = "D — Indústrias transformadoras — DI — Outros produtos minerais não metálicos";
const DJ = "D — Indústrias transformadoras — DJ — Metalurgia e produtos metálicos";
const DK = "D — Indústrias transformadoras — DK — Máquinas e equipamentos n. e.";
const DL = "D — Indústrias transformadoras — DL — Equipamento eléctrico e de óptica";
const DM = "D — Indústrias transformadoras — DM — Material de transporte";
const DN = "D — Indústrias transformadoras — DN — Outras n. e.";
const E = "E — Produção e distribuição de electricidade, gás e água";
const F = "F — Construção";
const G = "G — Comércio, serviços gerais e elementos comuns";
const H = "H — Alojamento e restauração";
const I = "I — Transportes, armazenagem e comunicações";
const J = "J — Telecomunicações e tecnologias de informação";
const K = "K — Actividades financeiras";
const L = "L — Saúde e acção social";
const M = "M — Outras actividades de serviços colectivos, sociais e pessoais";
const N = "N — Activo incorpóreo";

export const DEPRECIATION_CATEGORIES: DepreciationCategory[] = [
  // === A — Agricultura, pecuária, silvicultura, aquicultura, avicultura e pesca ===
  c("a-1-1", A, "A 1.1", "Barragens, diques, condutas e redes de rega e depósitos de elevação", 4, "edif"),
  c("a-1-2", A, "A 1.2", "Outras instalações em tijolo, pedra ou betão (armazéns, celeiros, silos)", 5, "edif"),
  c("a-1-3", A, "A 1.3", "Instalações em materiais ligeiros (madeira, zinco, fibrocimento)", 10, "edif"),
  c("a-1-4", A, "A 1.4", "Poços, furos, cercas e vedações", 20, "edif"),
  c("a-2-1", A, "A 2.1", "Equipamentos motorizados (tractores, ceifeiras, moto-cultivadores, etc.)", 16.66, "basico"),
  c("a-2-2", A, "A 2.2", "Equipamentos não motorizados", 12.5, "basico"),
  c("a-2-3", A, "A 2.3", "Máquinas de preparação, selecção, lavagem, empacotamento e embalagem", 16.66, "basico"),
  c("a-2-4", A, "A 2.4", "Máquinas secadoras", 6.67, "basico"),
  c("a-2-5", A, "A 2.5", "Equipamento de ordenha", 12.5, "basico"),
  c("a-2-6", A, "A 2.6", "Incubadoras", 10, "basico"),
  c("a-2-7", A, "A 2.7", "Outras máquinas e equipamentos da exploração agrícola ou pecuária", 10, "basico"),
  c("a-3-1", A, "A 3.1", "Pomares", 6.67, "outr"),
  c("a-3-2", A, "A 3.2", "Plantações várias", 10, "outr"),
  c("a-4-1", A, "A 4.1", "Gado bovino, suíno, caprino, ovino e cavalar", 20, "outr"),
  c("a-4-2", A, "A 4.2", "Galos, galinhas, patos, perus e outros ovíparos de criação rápida", 50, "outr"),
  c("a-4-3", A, "A 4.3", "Outros animais vivos", 14.28, "outr"),
  c("a-5-1", A, "A 5.1", "Terrenos em exploração — Agricultura", 4, "terra"),
  c("a-5-2", A, "A 5.2", "Terrenos em exploração — Silvicultura", 4, "terra"),
  c("a-5-3", A, "A 5.3", "Terrenos em exploração — Aquicultura", 2, "terra"),

  // === B — Pesca ===
  c("b-1-1", B, "B 1.1", "Barcos de pesca costeiros (traineiras, pequeno calado)", 12.5, "trans"),
  c("b-1-2", B, "B 1.2", "Barcos de alto mar — de ferro", 7.14, "trans"),
  c("b-1-3", B, "B 1.3", "Barcos de alto mar — de madeira", 10, "trans"),
  c("b-1-4", B, "B 1.4", "Barcos de alto mar — de fibra de vidro", 10, "trans"),
  c("b-1-5", B, "B 1.5", "Navios-fábricas e navios-frigoríficos", 7.14, "trans"),
  c("b-1-6", B, "B 1.6", "Aparelhos localizadores, detectores, telefonia, radiogoniometria e radar", 20, "basico"),
  c("b-1-7", B, "B 1.7", "Aprestos de pesca", 33.33, "ferr"),
  c("b-2-1", B, "B 2.1", "Embarcadouros e instalações de carga e descarga", 7.14, "edif"),
  c("b-2-2", B, "B 2.2", "Viveiros", 8.33, "edif"),
  c("b-2-3", B, "B 2.3", "Secadores", 6.67, "edif"),
  c("b-2-4", B, "B 2.4", "Instalações para limpeza e primeira preparação dos produtos da pesca", 5, "edif"),
  c("b-2-5", B, "B 2.5", "Instalações de conservação e congelação dos produtos da pesca", 10, "edif"),
  c("b-3-1", B, "B 3.1", "Máquinas e equipamentos para secagem", 12.5, "basico"),
  c("b-3-2", B, "B 3.2", "Máquinas e equipamentos de preparação, conservação, embalagem e congelação", 12.5, "basico"),
  c("b-4-1", B, "B 4.1", "Ponte-cais de betão", 3.33, "edif"),
  c("b-4-2", B, "B 4.2", "Ponte-cais de madeira", 6.25, "edif"),
  c("b-4-3", B, "B 4.3", "Ponte-cais de ferro", 8.33, "edif"),

  // === C — Indústrias extractivas ===
  c("c-1-2", C, "C 1.2", "Terrenos destinados a entulheiras", 4, "terra"),
  c("c-2-1", C, "C 2.1", "Instalações para separação e tratamento primário", 12.5, "edif"),
  c("c-2-2", C, "C 2.2", "Instalações para trituração, moagem e classificação", 12.5, "edif"),
  c("c-2-3", C, "C 2.3", "Instalações auxiliares", 10, "edif"),
  c("c-2-4", C, "C 2.4", "Vias férreas e respectivo material circulante", 6.67, "edif"),
  c("c-3-1", C, "C 3.1", "Equipamento mineiro fixo — de superfície", 12.5, "basico"),
  c("c-3-2", C, "C 3.2", "Equipamento mineiro fixo — de subsolo", 20, "basico"),
  c("c-3-3", C, "C 3.3", "Equipamento móvel sobre rodas ou lagartas", 20, "basico"),
  c("c-3-4", C, "C 3.4", "Ferramentas e utensílios de uso específico", 33.33, "ferr"),

  // === DA — Alimentares, bebidas e tabaco ===
  c("da-1-1", DA, "DA 1.1", "Silos", 5, "edif"),
  c("da-1-2", DA, "DA 1.2", "Depósitos e tanques", 6.67, "edif"),
  c("da-1-3", DA, "DA 1.3", "Fornos fixos", 12.5, "basico"),
  c("da-1-4", DA, "DA 1.4", "Fornos móveis", 16.67, "basico"),
  c("da-1-5", DA, "DA 1.5", "Máquinas e equipamentos de recepção e produção", 12.5, "basico"),
  c("da-1-6", DA, "DA 1.6", "Máquinas e equipamentos de embalagem e rotulagem", 10, "basico"),
  c("da-1-7", DA, "DA 1.7", "Máquinas e equipamentos de cozinha", 14.28, "basico"),
  c("da-1-8", DA, "DA 1.8", "Instalações frigoríficas e de ventilação", 12.5, "basico"),
  c("da-2-1", DA, "DA 2.1", "Bebidas — Instalações de captação, poços e depósitos de água", 5, "edif"),
  c("da-2-2", DA, "DA 2.2", "Bebidas — Tanques, cubas e depósitos metálicos", 6.66, "basico"),
  c("da-2-3", DA, "DA 2.3", "Bebidas — Tanques, cubas e depósitos de betão e similares", 5, "edif"),
  c("da-2-4", DA, "DA 2.4", "Bebidas — Caldeiras e alambiques", 6.66, "basico"),
  c("da-2-5", DA, "DA 2.5", "Bebidas — Máquinas e equipamentos de recepção e produção", 12.5, "basico"),
  c("da-2-6", DA, "DA 2.6", "Bebidas — Enchimento, engarrafamento, rotulagem e embalagem", 10, "basico"),
  c("da-2-7", DA, "DA 2.7", "Bebidas — Instalações frigoríficas e de ventilação", 12.5, "basico"),
  c("da-3-1", DA, "DA 3.1", "Tabaco — Câmaras de secagem de betão ou alvenaria", 5, "edif"),
  c("da-3-2", DA, "DA 3.2", "Tabaco — Câmaras de secagem de construção ligeira", 12.5, "edif"),
  c("da-3-3", DA, "DA 3.3", "Tabaco — Maquinaria e instalações de uso específico", 12.5, "basico"),

  // === DB — Têxtil ===
  c("db-1-1", DB, "DB 1.1", "Máquinas para fabrico de fio de malha e tecidos", 12.5, "basico"),
  c("db-1-2", DB, "DB 1.2", "Máquinas para branqueamento, tinturaria e estamparia", 14.28, "basico"),
  c("db-1-3", DB, "DB 1.3", "Máquinas para cordas, cabos, redes e outras fibras duras", 12.5, "basico"),
  c("db-1-4", DB, "DB 1.4", "Teares para a indústria de tapeçarias", 12.5, "basico"),
  c("db-1-5", DB, "DB 1.5", "Outras máquinas e equipamentos de uso específico", 10, "basico"),
  c("db-2-1", DB, "DB 2.1", "Vestuário — Máquinas para confecção de peças de vestuário", 12.5, "basico"),

  // === DC — Couro ===
  c("dc-1-1", DC, "DC 1.1", "Curtumes — Instalações industriais de uso específico", 12.5, "edif"),
  c("dc-1-2", DC, "DC 1.2", "Curtumes — Máquinas e equipamentos de uso específico", 14.28, "basico"),
  c("dc-2-1", DC, "DC 2.1", "Calçado — Máquinas e equipamentos de uso específico", 12.5, "basico"),
  c("dc-2-2", DC, "DC 2.2", "Calçado — Caldeiras para produção de vapor", 20, "basico"),
  c("dc-2-3", DC, "DC 2.3", "Calçado — Moldes e formas", 33.33, "ferr"),

  // === DD — Madeira e cortiça ===
  c("dd-1-1", DD, "DD 1.1", "Madeira — Silos e depósitos de uso específico", 6.67, "edif"),
  c("dd-1-2", DD, "DD 1.2", "Madeira — Máquinas de serração, arrasto, elevação e carga", 12.5, "basico"),
  c("dd-1-3", DD, "DD 1.3", "Madeira — Máquinas de corte, trituração, prensagem, secagem", 12.5, "basico"),
  c("dd-2-1", DD, "DD 2.1", "Obras de madeira — Silos e depósitos de uso específico", 6.67, "edif"),
  c("dd-2-2", DD, "DD 2.2", "Obras de madeira — Caldeiras a vapor", 20, "basico"),
  c("dd-2-3", DD, "DD 2.3", "Obras de madeira — Autoclaves de cocção", 14.28, "basico"),
  c("dd-2-4", DD, "DD 2.4", "Obras de madeira — Fornos de fogo semidirecto", 12.5, "basico"),
  c("dd-2-5", DD, "DD 2.5", "Outras máquinas — folheados, contraplacados, aglomerados", 12.5, "basico"),
  c("dd-2-6", DD, "DD 2.6", "Outras máquinas e equipamentos de uso específico", 10, "basico"),

  // === DE — Papel, cartão, edição, impressão ===
  c("de-1-1", DE, "DE 1.1", "Depósitos para preparação de pasta de papel", 6.67, "edif"),
  c("de-1-2", DE, "DE 1.2", "Máquinas para produção de pasta de papel", 12.5, "basico"),
  c("de-1-3", DE, "DE 1.3", "Máquinas para produção de papel e cartão", 10, "basico"),
  c("de-1-4", DE, "DE 1.4", "Máquinas para transformação de papel e cartão", 14.28, "basico"),
  c("de-2-1", DE, "DE 2.1", "Edição — Composição de jornais, revistas e publicações", 20, "basico"),
  c("de-2-2", DE, "DE 2.2", "Impressão por laser", 14.28, "basico"),
  c("de-2-3", DE, "DE 2.3", "Impressão por outros sistemas", 12.5, "basico"),
  c("de-2-4", DE, "DE 2.4", "Outras máquinas e apetrechos de uso específico", 10, "basico"),
  c("de-2-5", DE, "DE 2.5", "Moldes e matrizes", 33.33, "ferr"),

  // === DF — Coque e refinados petrolíferos ===
  c("df-1-1", DF, "DF 1.1", "Instalações industriais sujeitas a corrosão", 14.28, "edif"),
  c("df-1-2", DF, "DF 1.2", "Outras instalações industriais", 10, "edif"),
  c("df-1-3", DF, "DF 1.3", "Oleodutos e instalações de distribuição e transporte", 8.33, "basico"),
  c("df-1-4", DF, "DF 1.4", "Reservatórios", 5, "basico"),
  c("df-1-5", DF, "DF 1.5", "Bombas de gás (petróleo)", 10, "basico"),

  // === DG — Químicos e fibras sintéticas ===
  c("dg-1-1", DG, "DG 1.1", "Fornos reactores para síntese", 16.66, "basico"),
  c("dg-1-2", DG, "DG 1.2", "Fornos reactores para fusão", 16.66, "basico"),
  c("dg-1-3", DG, "DG 1.3", "Instalações de electrólise e electrossíntese", 16.66, "basico"),
  c("dg-1-4", DG, "DG 1.4", "Instalações para fabrico de ácidos", 16.66, "basico"),
  c("dg-1-5", DG, "DG 1.5", "Outras instalações industriais", 10, "edif"),
  c("dg-1-6", DG, "DG 1.6", "Máquinas de uso específico sujeitas a corrosão", 14.28, "basico"),
  c("dg-1-7", DG, "DG 1.7", "Outras máquinas e equipamentos de uso específico", 10, "basico"),
  c("dg-1-8", DG, "DG 1.8", "Reservatórios", 5, "basico"),
  c("dg-1-9", DG, "DG 1.9", "Material de distribuição de gases (embalagens ar comprimido)", 12.5, "basico"),
  c("dg-2-1", DG, "DG 2.1", "Instalações para fabrico de produtos farmacêuticos", 16.66, "edif"),
  c("dg-2-2", DG, "DG 2.2", "Outras instalações industriais", 10, "edif"),
  c("dg-2-3", DG, "DG 2.3", "Máquinas de uso específico sujeitas a corrosão", 14.28, "basico"),
  c("dg-2-4", DG, "DG 2.4", "Outras máquinas e equipamentos de uso específico", 10, "basico"),
  c("dg-2-5", DG, "DG 2.5", "Reservatórios", 5, "basico"),
  c("dg-2-6", DG, "DG 2.6", "Aparelhos e utensílios de laboratório", 20, "basico"),
  c("dg-3-1", DG, "DG 3.1", "Fibras sintéticas — máquinas sujeitas a corrosão", 14.28, "basico"),
  c("dg-3-2", DG, "DG 3.2", "Fibras sintéticas — outras máquinas de uso específico", 10, "basico"),
  c("dg-3-3", DG, "DG 3.3", "Prensas", 6.67, "basico"),
  c("dg-3-4", DG, "DG 3.4", "Moldes e formas", 33.33, "ferr"),
  c("dg-3-5", DG, "DG 3.5", "Aparelhos e utensílios de laboratório", 20, "basico"),

  // === DH — Borracha e plásticos ===
  c("dh-1-1", DH, "DH 1.1", "Borracha — máquinas sujeitas a corrosão", 14.28, "basico"),
  c("dh-1-2", DH, "DH 1.2", "Borracha — outras máquinas de uso específico", 10, "basico"),
  c("dh-1-3", DH, "DH 1.3", "Borracha — moldes e formas", 33.33, "ferr"),
  c("dh-2-1", DH, "DH 2.1", "Plásticos — máquinas sujeitas a corrosão", 14.28, "basico"),
  c("dh-2-2", DH, "DH 2.2", "Plásticos — outras máquinas de uso específico", 10, "basico"),
  c("dh-2-3", DH, "DH 2.3", "Plásticos — moldes e formas", 33.33, "ferr"),
  c("dh-2-4", DH, "DH 2.4", "Plásticos — ferramentas e utensílios de uso específico", 33.33, "ferr"),

  // === DI — Outros minerais não metálicos ===
  c("di-1-1", DI, "DI 1.1", "Vidro — máquinas de trituração, moagem e mistura", 12.5, "basico"),
  c("di-1-2", DI, "DI 1.2", "Vidro — outras máquinas de uso específico", 10, "basico"),
  c("di-1-3", DI, "DI 1.3", "Vidro — fornos", 14.28, "basico"),
  c("di-1-4", DI, "DI 1.4", "Vidro — moldes, ferramentas e utensílios", 33.33, "ferr"),
  c("di-2-1", DI, "DI 2.1", "Terrenos de exploração, incluindo pedreiras", 10, "terra"),
  c("di-2-2", DI, "DI 2.2", "Máquinas de sondagem, extracção e remoção", 14.28, "basico"),
  c("di-2-3", DI, "DI 2.3", "Máquinas de compressão, trituração, selecção, corte", 14.28, "basico"),
  c("di-2-4", DI, "DI 2.4", "Outras máquinas e equipamentos industriais", 12.5, "basico"),
  c("di-2-5", DI, "DI 2.5", "Silos e depósitos", 6.67, "edif"),
  c("di-2-6", DI, "DI 2.6", "Fornos e muflas", 14.28, "basico"),
  c("di-2-7", DI, "DI 2.7", "Moldes e matrizes", 33.33, "ferr"),
  c("di-2-8", DI, "DI 2.8", "Ferramentas e utensílios de uso específico", 33.33, "ferr"),

  // === DJ — Metalurgia ===
  c("dj-1-1", DJ, "DJ 1.1", "Fornos para fundição", 12.5, "basico"),
  c("dj-1-2", DJ, "DJ 1.2", "Instalações para electrólise e outros processos químicos", 16.66, "basico"),
  c("dj-1-3", DJ, "DJ 1.3", "Máquinas e equipamentos industriais de uso específico", 14.28, "basico"),
  c("dj-1-4", DJ, "DJ 1.4", "Ferramentas e utensílios de uso específico", 20, "ferr"),
  c("dj-2-1", DJ, "DJ 2.1", "Fornos e estufas", 14.28, "basico"),
  c("dj-2-2", DJ, "DJ 2.2", "Instalações de vácuo", 20, "basico"),
  c("dj-2-3", DJ, "DJ 2.3", "Instalações para electrólise e outros processos químicos", 16.66, "basico"),
  c("dj-2-4", DJ, "DJ 2.4", "Máquinas e equipamentos industriais de uso específico", 12.5, "basico"),
  c("dj-2-5", DJ, "DJ 2.5", "Máquinas de bobinar", 25, "basico"),
  c("dj-2-6", DJ, "DJ 2.6", "Prensas e compressores", 12.5, "basico"),
  c("dj-2-7", DJ, "DJ 2.7", "Máquinas e aparelhos para soldadura", 16.66, "basico"),
  c("dj-2-8", DJ, "DJ 2.8", "Moldes e matrizes", 33.33, "ferr"),
  c("dj-2-9", DJ, "DJ 2.9", "Outras ferramentas e utensílios de uso específico", 20, "ferr"),

  // === DK — Máquinas e equipamentos n. e. ===
  c("dk-1-1", DK, "DK 1.1", "Fornos e estufas", 14.28, "basico"),
  c("dk-1-2", DK, "DK 1.2", "Instalações de vácuo", 20, "basico"),
  c("dk-1-3", DK, "DK 1.3", "Instalações para electrólise e outros processos químicos", 16.66, "basico"),
  c("dk-1-4", DK, "DK 1.4", "Máquinas e equipamentos industriais de uso específico", 12.5, "basico"),
  c("dk-1-5", DK, "DK 1.5", "Máquinas de bobinar", 25, "basico"),
  c("dk-1-6", DK, "DK 1.6", "Prensas e compressores", 12.5, "basico"),
  c("dk-1-7", DK, "DK 1.7", "Máquinas e aparelhos para soldadura", 16.66, "basico"),
  c("dk-1-8", DK, "DK 1.8", "Moldes e matrizes", 33.33, "ferr"),
  c("dk-1-9", DK, "DK 1.9", "Outras ferramentas e utensílios de uso específico", 20, "ferr"),

  // === DL — Equipamento eléctrico e de óptica ===
  c("dl-1-1", DL, "DL 1.1", "Fornos e estufas", 14.28, "basico"),
  c("dl-1-2", DL, "DL 1.2", "Máquinas e equipamentos industriais de uso específico", 12.5, "basico"),
  c("dl-1-3", DL, "DL 1.3", "Prensas e compressores", 12.5, "basico"),
  c("dl-1-4", DL, "DL 1.4", "Máquinas e aparelhos para soldadura", 16.66, "basico"),
  c("dl-1-5", DL, "DL 1.5", "Moldes e matrizes", 33.33, "ferr"),
  c("dl-1-6", DL, "DL 1.6", "Outras ferramentas e utensílios de uso específico", 20, "ferr"),

  // === DM — Material de transporte ===
  c("dm-1-1", DM, "DM 1.1", "Pistas de ensaio e prova", 6.67, "edif"),
  c("dm-1-2", DM, "DM 1.2", "Superfícies de estacionamento sem cobertura", 5, "edif"),
  c("dm-1-3", DM, "DM 1.3", "Fornos para fundição", 12.5, "basico"),
  c("dm-1-4", DM, "DM 1.4", "Linhas de montagem", 14.28, "basico"),
  c("dm-1-5", DM, "DM 1.5", "Máquinas e equipamentos para aplicação de pintura", 12.5, "basico"),
  c("dm-1-6", DM, "DM 1.6", "Transportadores e máquinas de alimentação de peças", 12.5, "basico"),
  c("dm-1-7", DM, "DM 1.7", "Contentores de transporte interno", 14.28, "basico"),
  c("dm-1-8", DM, "DM 1.8", "Máquinas e equipamentos de ensaio e medida", 14.28, "basico"),
  c("dm-1-9", DM, "DM 1.9", "Moldes e matrizes", 33.33, "ferr"),
  c("dm-1-10", DM, "DM 1.10", "Outras ferramentas e utensílios de uso específico", 33.33, "ferr"),
  c("dm-2-1", DM, "DM 2.1", "Naval — Docas flutuantes", 8.33, "edif"),
  c("dm-2-2", DM, "DM 2.2", "Naval — Docas secas, cais e pontes-cais", 5, "edif"),
  c("dm-2-3", DM, "DM 2.3", "Naval — Rebocadores e embarcações similares", 7.14, "trans"),
  c("dm-2-4", DM, "DM 2.4", "Naval — Gruas, guindastes e pórticos", 12.5, "basico"),
  c("dm-2-5", DM, "DM 2.5", "Naval — Fornos e estufas", 14.28, "basico"),
  c("dm-2-6", DM, "DM 2.6", "Naval — Instalações de vácuo", 20, "basico"),
  c("dm-2-7", DM, "DM 2.7", "Naval — Electrólise e outros processos químicos", 16.66, "basico"),
  c("dm-2-8", DM, "DM 2.8", "Naval — Máquinas industriais de uso específico", 12.5, "basico"),
  c("dm-2-9", DM, "DM 2.9", "Naval — Prensas e compressores", 12.5, "basico"),
  c("dm-2-10", DM, "DM 2.10", "Naval — Máquinas e aparelhos para soldadura", 16.66, "basico"),
  c("dm-2-11", DM, "DM 2.11", "Naval — Moldes e matrizes", 33.33, "ferr"),
  c("dm-2-12", DM, "DM 2.12", "Naval — Outras ferramentas e utensílios", 20, "ferr"),

  // === DN — Outras transformadoras ===
  c("dn-1-1", DN, "DN 1.1", "Máquinas de serração e corte", 14.28, "basico"),
  c("dn-1-2", DN, "DN 1.2", "Caldeiras e estufas", 12.5, "basico"),
  c("dn-1-3", DN, "DN 1.3", "Prensas e compressores", 12.5, "basico"),
  c("dn-1-4", DN, "DN 1.4", "Máquinas e aparelhos para soldadura", 16.66, "basico"),
  c("dn-1-5", DN, "DN 1.5", "Outras máquinas e equipamentos de uso específico", 14.28, "basico"),
  c("dn-1-6", DN, "DN 1.6", "Moldes e matrizes", 33.33, "ferr"),
  c("dn-1-7", DN, "DN 1.7", "Outras ferramentas e utensílios de uso específico", 20, "ferr"),

  // === E — Electricidade, gás e água ===
  c("e-1-1", E, "E 1.1", "Obras hidráulicas fixas", 3.33, "edif"),
  c("e-1-2-1", E, "E 1.2.1", "Equipamentos de centrais hidroeléctricas", 5, "basico"),
  c("e-1-2-2", E, "E 1.2.2", "Equipamentos de centrais termoeléctricas", 7.14, "basico"),
  c("e-1-2-3", E, "E 1.2.3", "Equipamentos de centrais eólicas", 8.33, "basico"),
  c("e-1-2-4", E, "E 1.2.4", "Equipamentos de centrais fotovoltaicas", 8.33, "basico"),
  c("e-1-3", E, "E 1.3", "Subestações e postos de transformação", 5, "basico"),
  c("e-1-4", E, "E 1.4", "Linhas de transporte (AT e BT) e suportes", 5, "basico"),
  c("e-1-5", E, "E 1.5", "Aparelhos de medida e controlo", 10, "basico"),
  c("e-1-6", E, "E 1.6", "Outras instalações técnicas", 8.33, "basico"),
  c("e-2-1", E, "E 2.1", "Gás — Instalações de produção", 8.33, "basico"),
  c("e-2-2", E, "E 2.2", "Gás — Gasómetros e depósitos para armazenagem", 6.25, "basico"),
  c("e-2-3", E, "E 2.3", "Gás — Redes de transporte e distribuição", 5, "basico"),
  c("e-2-4", E, "E 2.4", "Gás — Outras máquinas e instalações de uso específico", 12.5, "basico"),
  c("e-2-5", E, "E 2.5", "Gás — Aparelhos de medida e controlo", 10, "basico"),
  c("e-3-1", E, "E 3.1", "Vapor/água quente/gelo — máquinas e instalações", 12.5, "basico"),
  c("e-3-2", E, "E 3.2", "Vapor/água quente/gelo — aparelhos de medida e controlo", 10, "basico"),
  c("e-4-1", E, "E 4.1", "Água — Obras hidráulicas fixas", 3.33, "edif"),
  c("e-4-2", E, "E 4.2", "Água — Comportas", 5, "basico"),
  c("e-4-3", E, "E 4.3", "Água — Reservatórios, tanques e instalações elevatórias", 4, "edif"),
  c("e-4-4", E, "E 4.4", "Água — Redes de distribuição", 5, "basico"),
  c("e-4-5", E, "E 4.5", "Água — Máquinas e equipamentos de uso específico", 10, "basico"),
  c("e-4-6", E, "E 4.6", "Água — Aparelhos de medida e controlo", 10, "basico"),
  c("e-4-7", E, "E 4.7", "Motores e geradores eléctricos abaixo de 22 kVAs", 20, "basico"),
  c("e-4-8", E, "E 4.8", "Motores e geradores eléctricos acima de 22 kVAs", 10, "basico"),

  // === F — Construção ===
  c("f-1", F, "F 1", "Construções ligeiras não afectas a obras em curso", 12.5, "edif"),
  c("f-2", F, "F 2", "Material de desenho, topografia, ensaio e medida", 14.28, "basico"),
  c("f-3-1", F, "F 3.1", "Materiais auxiliares — Andaimes", 14.28, "outr"),
  c("f-3-2", F, "F 3.2", "Materiais auxiliares — Cofragem", 25, "outr"),
  c("f-3-3", F, "F 3.3", "Materiais auxiliares — diversos", 20, "outr"),
  c("f-4-1", F, "F 4.1", "Gruas e guindastes", 12.5, "basico"),
  c("f-4-2", F, "F 4.2", "Equipamentos de transporte geral", 25, "trans"),
  c("f-4-3", F, "F 4.3", "Oficinas de carpintaria e serralharia", 16.66, "basico"),
  c("f-4-4", F, "F 4.4", "Produção e distribuição de energia eléctrica", 14.28, "basico"),
  c("f-4-5", F, "F 4.5", "Movimentação e armazenagem de materiais", 14.28, "basico"),
  c("f-4-6", F, "F 4.6", "Trabalhos de ar comprimido", 25, "basico"),
  c("f-4-7", F, "F 4.7", "Escavação e terraplanagem", 20, "basico"),
  c("f-4-8", F, "F 4.8", "Sondagens e fundações", 20, "basico"),
  c("f-4-9", F, "F 4.9", "Pedreiras, fabricação e aplicação de betões e argamassas", 20, "basico"),
  c("f-4-10", F, "F 4.10", "Construção de estradas", 20, "basico"),
  c("f-4-11", F, "F 4.11", "Obras hidráulicas", 6.25, "basico"),
  c("f-5", F, "F 5", "Ferramentas e equipamentos individuais", 33.33, "ferr"),

  // === G — Comércio, serviços gerais e elementos comuns ===
  c("g-1-1", G, "G 1.1", "Edifícios industriais", 4, "edif"),
  c("g-1-2", G, "G 1.2", "Edifícios industriais sujeitos a corrosão", 5, "edif"),
  c("g-1-3", G, "G 1.3", "Edifícios comerciais e administrativos", 4, "edif"),
  c("g-1-4", G, "G 1.4", "Edifícios habitacionais", 2, "edif"),
  c("g-1-5", G, "G 1.5", "Edifícios — saúde, ensino, serviços recreativos e culturais", 4, "edif"),
  c("g-1-6", G, "G 1.6", "Construções ligeiras (fibrocimento, madeira, metais)", 12.5, "edif"),
  c("g-1-7", G, "G 1.7", "Obras hidráulicas, incluindo poços de água", 10, "edif"),
  c("g-1-8", G, "G 1.8", "Obras de pavimentação (pedra, cimento, betão, asfalto)", 10, "edif"),
  c("g-1-9", G, "G 1.9", "Pontes e aquedutos em betão ou alvenaria", 3.33, "edif"),
  c("g-1-10", G, "G 1.10", "Pontes e aquedutos metálicos", 8.33, "edif"),
  c("g-1-11", G, "G 1.11", "Pontes e aquedutos em madeira", 20, "edif"),
  c("g-1-12", G, "G 1.12", "Silos, reservatórios e outros depósitos", 5, "edif"),
  c("g-1-13", G, "G 1.13", "Muros", 6.67, "edif"),
  c("g-1-14", G, "G 1.14", "Vedações ligeiras (madeira, arame)", 25, "edif"),
  c("g-1-15", G, "G 1.15", "Arranjos urbanísticos", 25, "edif"),
  c("g-1-16", G, "G 1.16", "Via-férrea (actividade ferroviária)", 2, "edif"),
  c("g-1-17", G, "G 1.17", "Pontes e obras de arte (actividade ferroviária)", 2.5, "edif"),
  c("g-2-1", G, "G 2.1", "Instalações de água, electricidade, ar comprimido e refrigeração central", 10, "basico"),
  c("g-2-2", G, "G 2.2", "Redes de cabos aéreos e respectivos suportes", 6.67, "basico"),
  c("g-2-3", G, "G 2.3", "Postos de transformação", 10, "basico"),
  c("g-2-4", G, "G 2.4", "Ascensores, monta-cargas e escadas mecânicas", 10, "basico"),
  c("g-2-5", G, "G 2.5", "Captação e distribuição de água (privativas)", 12.5, "basico"),
  c("g-2-6", G, "G 2.6", "Carga, descarga e embarque (privativas)", 7.14, "basico"),
  c("g-2-7", G, "G 2.7", "Centrais telefónicas e outras comunicações (rádio, TV)", 16.66, "basico"),
  c("g-2-8", G, "G 2.8", "Distribuição de combustíveis líquidos", 10, "basico"),
  c("g-2-9", G, "G 2.9", "Segurança, detecção e extinção de incêndios", 12.5, "basico"),
  c("g-2-10", G, "G 2.10", "Instalações divisórias em escritórios", 20, "adm"),
  c("g-2-11-1", G, "G 2.11.1", "Armazenagem e depósito — De betão", 5, "edif"),
  c("g-2-11-2", G, "G 2.11.2", "Armazenagem e depósito — De madeira", 20, "edif"),
  c("g-2-11-3", G, "G 2.11.3", "Armazenagem e depósito — Metálicas", 12.5, "edif"),
  c("g-2-12", G, "G 2.12", "Reservatórios para combustíveis líquidos", 6.66, "basico"),
  c("g-2-13", G, "G 2.13", "Refeitórios e cozinhas privativas", 10, "basico"),
  c("g-2-14", G, "G 2.14", "Vitrinas e estantes fixas", 20, "adm"),
  c("g-2-15", G, "G 2.15", "Vitrinas, estantes e expositores móveis", 33.33, "adm"),
  c("g-2-16", G, "G 2.16", "Estações (actividade ferroviária)", 4, "edif"),
  c("g-2-17", G, "G 2.17", "Apeadeiros (actividade ferroviária)", 4, "edif"),
  c("g-2-18", G, "G 2.18", "Instalações não especificadas", 10, "basico"),
  c("g-3-1", G, "G 3.1", "Computadores e outros equipamentos para tratamento de informação", 33.33, "adm"),
  c("g-3-2", G, "G 3.2", "Electrónicos — automatização, regulação e supervisão", 20, "basico"),
  c("g-3-3", G, "G 3.3", "Máquinas de cópia (fotocopiadoras, scanners, fax)", 25, "adm"),
  c("g-3-4", G, "G 3.4", "Impressoras", 33.33, "adm"),
  c("g-3-5", G, "G 3.5", "Televisores, plasmas, monitores, projectores de vídeo", 25, "adm"),
  c("g-3-6", G, "G 3.6", "Outras máquinas e equipamentos electrónicos", 20, "basico"),
  c("g-3-7", G, "G 3.7", "Conservação e manutenção", 12.5, "basico"),
  c("g-3-8", G, "G 3.8", "Motores, incluindo geradores", 25, "basico"),
  c("g-3-9", G, "G 3.9", "Máquinas-ferramentas ligeiras", 20, "basico"),
  c("g-3-10", G, "G 3.10", "Máquinas-ferramentas pesadas", 12.5, "basico"),
  c("g-3-11", G, "G 3.11", "Material contra incêndios (extintores e outros)", 25, "basico"),
  c("g-3-12", G, "G 3.12", "Aparelhos de ar condicionado e ventilação", 12.5, "basico"),
  c("g-3-13", G, "G 3.13", "Aparelhos de laboratório e precisão", 14.28, "basico"),
  c("g-3-14", G, "G 3.14", "Aparelhos de medida e controlo", 12.5, "basico"),
  c("g-3-15", G, "G 3.15", "Telefones fixos", 16.67, "adm"),
  c("g-3-16", G, "G 3.16", "Telefones móveis", 33.33, "adm"),
  c("g-3-17", G, "G 3.17", "Máquinas, equipamentos e aparelhos não especificados", 12.5, "basico"),
  c("g-4-1-1", G, "G 4.1.1", "Veículos automóveis — Pesados", 16.67, "trans"),
  c("g-4-1-2", G, "G 4.1.2", "Veículos automóveis — Ligeiros", 25, "trans"),
  c("g-4-1-3", G, "G 4.1.3", "Veículos automóveis — Mistos", 20, "trans"),
  c("g-4-2", G, "G 4.2", "Veículos funerários", 20, "trans"),
  c("g-4-3", G, "G 4.3", "Tractores, atrelados, empilhadores e camiões basculantes", 14.28, "trans"),
  c("g-4-4", G, "G 4.4", "Bicicletas e motociclos", 25, "trans"),
  c("g-4-5", G, "G 4.5", "Barcos de ferro", 7.14, "trans"),
  c("g-4-6", G, "G 4.6", "Barcos de madeira", 10, "trans"),
  c("g-4-7", G, "G 4.7", "Barcos de borracha", 12.5, "trans"),
  c("g-4-8", G, "G 4.8", "Barcos de fibra de vidro", 20, "trans"),
  c("g-4-9", G, "G 4.9", "Locomotivas e automotoras", 5, "trans"),
  c("g-4-10", G, "G 4.10", "Vagões", 4, "trans"),
  c("g-4-11", G, "G 4.11", "Vias-férreas", 4, "edif"),
  c("g-4-12", G, "G 4.12", "Aeronaves", 5, "trans"),
  c("g-5-1", G, "G 5.1", "Artigos de conforto e decoração", 20, "adm"),
  c("g-5-2", G, "G 5.2", "Equipamento publicitário colocado na via pública", 12.5, "outr"),
  c("g-5-3", G, "G 5.3", "Filmes, discos e cassetes", 25, "outr"),
  c("g-5-4", G, "G 5.4", "Material de desenho e topografia", 12.5, "basico"),
  c("g-5-5-1", G, "G 5.5.1", "Mobiliário de madeira", 16.67, "adm"),
  c("g-5-5-2", G, "G 5.5.2", "Mobiliário de outros materiais", 12.5, "adm"),
  c("g-5-6", G, "G 5.6", "Moldes, matrizes, formas e cunhos", 25, "ferr"),
  c("g-5-7", G, "G 5.7", "Taras, vasilhame e embalagens de madeira", 20, "outr"),
  c("g-5-8", G, "G 5.8", "Taras, vasilhame e embalagens de metal", 14.28, "outr"),
  c("g-5-9", G, "G 5.9", "Contentores", 8.33, "outr"),
  c("g-5-10", G, "G 5.10", "Encerados", 50, "outr"),
  c("g-5-11", G, "G 5.11", "Ferramentas e utensílios de oficinas", 14.28, "ferr"),
  c("g-5-12", G, "G 5.12", "Outras ferramentas e utensílios", 25, "ferr"),

  // === H — Alojamento e restauração ===
  c("h-1-1", H, "H 1.1", "Edifícios destinados a hotelaria e restauração", 4, "edif"),
  c("h-1-2", H, "H 1.2", "Decorações interiores, incluindo tapeçarias", 25, "adm"),
  c("h-1-3", H, "H 1.3", "Máquinas de lavandaria, centrifugação e secagem", 20, "basico"),
  c("h-1-4", H, "H 1.4", "Equipamentos sanitários, cozinha e outros de uso específico", 14.28, "basico"),
  c("h-1-5", H, "H 1.5", "Equipamentos desportivos e de recreio", 10, "outr"),
  c("h-1-6", H, "H 1.6", "Mobiliário de quartos, salas, salões e outras dependências", 10, "adm"),
  c("h-1-7", H, "H 1.7", "Colchoaria e cobertores", 33.33, "outr"),
  c("h-1-8", H, "H 1.8", "Roupas brancas e atoalhados", 50, "outr"),
  c("h-1-9", H, "H 1.9", "Louças e objectos de vidro (excepto decorativos)", 33.33, "outr"),
  c("h-1-10", H, "H 1.10", "Talheres e utensílios de cozinha", 50, "outr"),

  // === I — Transportes, armazenagem e comunicações ===
  c("i-1-1-1", I, "I 1.1.1", "Ferroviário — Túneis e obras de arte", 2, "edif"),
  c("i-1-1-2", I, "I 1.1.2", "Ferroviário — Redes e canalizações subterrâneas", 5, "edif"),
  c("i-1-1-3", I, "I 1.1.3", "Ferroviário — Vias férreas", 6.67, "edif"),
  c("i-1-1-4", I, "I 1.1.4", "Ferroviário — Subestações e postos de transformação", 5, "basico"),
  c("i-1-1-5", I, "I 1.1.5", "Ferroviário — Linhas eléctricas e respectivas instalações", 5, "basico"),
  c("i-1-1-6", I, "I 1.1.6", "Ferroviário — Sinalização, controlo e comunicação", 12.5, "basico"),
  c("i-1-1-7", I, "I 1.1.7", "Ferroviário — Locomotivas e automotoras", 7.14, "trans"),
  c("i-1-1-8", I, "I 1.1.8", "Ferroviário — Vagões", 6.25, "trans"),
  c("i-1-1-9", I, "I 1.1.9", "Ferroviário — Carruagens", 5, "trans"),
  c("i-1-1-10", I, "I 1.1.10", "Ferroviário — Máquinas e equipamentos de carga e descarga", 8.33, "basico"),
  c("i-1-1-11", I, "I 1.1.11", "Ferroviário — Manutenção da via", 10, "basico"),
  c("i-1-1-12", I, "I 1.1.12", "Ferroviário — Oficinas de reparação e revisão", 12.5, "basico"),
  c("i-1-2-1", I, "I 1.2.1", "Rodoviários — Veículos automóveis de serviço público (pesados, ligeiros, mistos)", 25, "trans"),
  c("i-1-2-2", I, "I 1.2.2", "Rodoviários — Equipamentos de comunicação", 25, "basico"),
  c("i-1-2-3", I, "I 1.2.3", "Rodoviários — Carga e descarga", 12.5, "basico"),
  c("i-1-2-4", I, "I 1.2.4", "Rodoviários — Oficinas de reparação e revisão", 12.5, "basico"),
  c("i-2-1", I, "I 2.1", "Navios de carga geral e mistos de passageiros e carga", 10, "trans"),
  c("i-2-2", I, "I 2.2", "Navios de passageiros, ferries, graneleiros, porta-contentores, tanque, frigorífico", 8.33, "trans"),
  c("i-2-3", I, "I 2.3", "Dragas, gruas flutuantes, barcaças (ferro)", 8.33, "trans"),
  c("i-2-4", I, "I 2.4", "Fragatas, barcaças e outras embarcações de madeira", 10, "trans"),
  c("i-2-5", I, "I 2.5", "Embarcações de borracha", 10, "trans"),
  c("i-2-6", I, "I 2.6", "Embarcações de fibra de vidro", 25, "trans"),
  c("i-2-7", I, "I 2.7", "Máquinas e instalações portuárias", 10, "basico"),
  c("i-2-8", I, "I 2.8", "Oficinas de reparação e revisão (navais)", 12.5, "basico"),
  c("i-3-1", I, "I 3.1", "Aviões com motores de reacção", 10, "trans"),
  c("i-3-2", I, "I 3.2", "Aviões com motores a turbo-hélice", 12.5, "trans"),
  c("i-3-3", I, "I 3.3", "Aviões com motores convencionais", 25, "trans"),
  c("i-3-4", I, "I 3.4", "Frota terrestre", 20, "trans"),
  c("i-3-5", I, "I 3.5", "Equipamentos auxiliares aeroportuários (carga, embarque)", 10, "basico"),
  c("i-3-6", I, "I 3.6", "Oficinas de reparação e revisão (aéreo)", 12.5, "basico"),
  c("i-4-1", I, "I 4.1", "Telecom — Centrais de transmissão e recepção por satélite", 20, "basico"),
  c("i-4-2", I, "I 4.2", "Telecom — Outras centrais de transmissão e recepção", 20, "basico"),
  c("i-4-3", I, "I 4.3", "Telecom — Redes aéreas e respectivos suportes", 5, "basico"),
  c("i-4-4", I, "I 4.4", "Telecom — Cabos subterrâneos", 10, "basico"),
  c("i-4-5", I, "I 4.5", "Telecom — Cabos submarinos", 5, "basico"),
  c("i-4-6", I, "I 4.6", "Telecom — Sincronização, controlo, comutação analógica e digital", 20, "basico"),
  c("i-4-7", I, "I 4.7", "Telecom — Antenas de radiocomunicação", 10, "basico"),
  c("i-4-8", I, "I 4.8", "Telecom — Postos públicos e particulares", 10, "basico"),
  c("i-5-1", I, "I 5.1", "Aeroporto — Pavimento flexível de pista de aviação", 6.67, "edif"),
  c("i-5-2", I, "I 5.2", "Aeroporto — Pavimento flexível de caminhos de circulação", 8.33, "edif"),
  c("i-5-3", I, "I 5.3", "Aeroporto — Pavimento rígido de pista", 5, "edif"),
  c("i-5-4", I, "I 5.4", "Aeroporto — Pavimento rígido para caminho de circulação", 6.67, "edif"),
  c("i-5-5", I, "I 5.5", "Aeroporto — Pavimento flexível da placa de estacionamento", 6.67, "edif"),
  c("i-5-6", I, "I 5.6", "Aeroporto — Heliportos de pavimento flexível", 6.67, "edif"),
  c("i-5-7", I, "I 5.7", "Aeroporto — Helidecks suportados por navios", 7.15, "edif"),
  c("i-5-8", I, "I 5.8", "Aeroporto — Terminais de passageiros em alvenaria", 6.67, "edif"),
  c("i-5-9", I, "I 5.9", "Aeroporto — Outras infra-estruturas", 10, "edif"),
  c("i-6-1", I, "I 6.1", "Equipamentos aeronáuticos — ILS", 10, "basico"),
  c("i-6-2", I, "I 6.2", "Equipamentos aeronáuticos — HF", 12.5, "basico"),
  c("i-6-3", I, "I 6.3", "Equipamentos aeronáuticos — VHF", 10, "basico"),
  c("i-6-4", I, "I 6.4", "Equipamentos aeronáuticos — CVOR", 12.5, "basico"),
  c("i-6-5", I, "I 6.5", "Equipamentos aeronáuticos — DVOR", 10, "basico"),
  c("i-6-6", I, "I 6.6", "Equipamentos aeronáuticos — ADS-C", 8.33, "basico"),
  c("i-6-7", I, "I 6.7", "Equipamentos aeronáuticos — RADAR secundário", 7.15, "basico"),
  c("i-6-8", I, "I 6.8", "Equipamentos aeronáuticos — Simulador de tráfego aéreo", 14.28, "basico"),
  c("i-6-9", I, "I 6.9", "Equipamentos aeronáuticos — PAPI", 16.67, "basico"),
  c("i-7-1", I, "I 7.1", "Assistência em terra — Mangas ou escadas telescópicas", 10, "basico"),
  c("i-7-2", I, "I 7.2", "Assistência em terra — Loader (carregador de porão)", 5, "basico"),
  c("i-7-3", I, "I 7.3", "Assistência em terra — Trailer", 5, "trans"),
  c("i-7-4", I, "I 7.4", "Assistência em terra — Tractor rebocador", 10, "trans"),
  c("i-7-5", I, "I 7.5", "Assistência em terra — Veículo lavabos", 10, "trans"),
  c("i-7-6", I, "I 7.6", "Assistência em terra — Ambolice (passageiros com incapacidade física)", 6.67, "trans"),
  c("i-7-7", I, "I 7.7", "Assistência em terra — Aspirador de bordo da aeronave", 20, "basico"),
  c("i-7-8", I, "I 7.8", "Assistência em terra — Autocarro de passageiros com suspensão pneumática", 6.67, "trans"),
  c("i-7-9", I, "I 7.9", "Assistência em terra — Autocarro VIP", 10, "trans"),
  c("i-8-1", I, "I 8.1", "Combate a incêndio — Veículos", 10, "trans"),
  c("i-8-2", I, "I 8.2", "Combate a incêndio — Espuma para incêndio", 10, "outr"),
  c("i-8-3", I, "I 8.3", "Combate a incêndio — Vestuário de protecção ao fogo", 10, "outr"),
  c("i-9-1", I, "I 9.1", "Segurança — Raio-X", 20, "basico"),
  c("i-9-2", I, "I 9.2", "Segurança — Pórtico detector de metais", 20, "basico"),
  c("i-9-3", I, "I 9.3", "Segurança — Detector portátil de metais", 20, "basico"),
  c("i-9-4", I, "I 9.4", "Segurança — Circuito fechado de TV (CCTV)", 50, "basico"),
  c("i-9-5", I, "I 9.5", "Segurança — Sistema de detecção de explosivos (EDS)", 10, "basico"),
  c("i-10-1", I, "I 10.1", "Material circulante — Locomotivas", 7.15, "trans"),
  c("i-10-2", I, "I 10.2", "Material circulante — Vagões", 5.55, "trans"),
  c("i-10-3", I, "I 10.3", "Material circulante — Carruagens", 5.55, "trans"),
  c("i-10-4", I, "I 10.4", "Material circulante — Furgões", 5.55, "trans"),
  c("i-10-5", I, "I 10.5", "Material circulante — Powercar", 5.55, "trans"),
  c("i-10-6", I, "I 10.6", "Material circulante — Porta contentor", 5.55, "trans"),
  c("i-10-7", I, "I 10.7", "Material circulante — Cisterna de combustível", 5.55, "trans"),
  c("i-10-8", I, "I 10.8", "Material circulante — Automóvel de linha (zorras, locotractores)", 5.55, "trans"),

  // === J — Telecomunicações e TI ===
  c("j-1-1", J, "J 1.1", "Aparelho de medição e orientação", 10, "basico"),
  c("j-1-2", J, "J 1.2", "Equipamento de processamento de dados", 33.33, "adm"),
  c("j-1-3", J, "J 1.3", "Grupos electrogéneos e conversores rotativos eléctricos", 16.66, "basico"),
  c("j-1-4", J, "J 1.4", "Transformadores eléctricos, conversores eléctricos estáticos", 20, "basico"),
  c("j-1-5", J, "J 1.5", "Máquina electromecânica de motor eléctrico para tosquiar", 20, "basico"),
  c("j-1-6", J, "J 1.6", "Fornos eléctricos industriais ou de laboratório", 10, "basico"),
  c("j-1-7", J, "J 1.7", "Máquinas para soldar eléctrico, laser, ultra-som, jacto de plasma", 10, "basico"),
  c("j-1-8", J, "J 1.8", "Aparelhos eléctricos para aquecimento", 10, "basico"),
  c("j-1-9", J, "J 1.9", "Gravadores de dados de voo", 20, "basico"),
  c("j-1-10", J, "J 1.10", "Radiodetecção, radio sondagem (radar), radionavegação e radio telecomando", 16.66, "basico"),
  c("j-1-11", J, "J 1.11", "Binóculos, lunetas, telescópios ópticos (excepto radioastronomia)", 16.66, "basico"),
  c("j-1-12", J, "J 1.12", "Microscópios ópticos e não ópticos, difratógrafos", 10, "basico"),
  c("j-1-13", J, "J 1.13", "Bússolas, agulhas de marear, aparelho de navegação", 10, "basico"),
  c("j-1-14", J, "J 1.14", "Geodesia, topografia, hidrografia, oceanografia, meteorologia", 6.66, "basico"),
  c("j-1-15", J, "J 1.15", "Estação Meteorológica", 20, "basico"),
  c("j-1-16", J, "J 1.16", "Estação Sísmica", 10, "basico"),
  c("j-1-17", J, "J 1.17", "Centrais de transmissão e recepção por satélite", 20, "basico"),
  c("j-1-18", J, "J 1.18", "Cabos subterrâneos", 8.33, "basico"),
  c("j-1-19", J, "J 1.19", "Cabos submarinos", 6.66, "basico"),
  c("j-1-20", J, "J 1.20", "Outros instrumentos e aparelhos não especificados", 10, "basico"),

  // === K — Actividades financeiras ===
  c("k-1-1", K, "K 1.1", "Equipamentos de segurança, prevenção e vigilância", 12.5, "basico"),
  c("k-1-2", K, "K 1.2", "Cofres e casas fortes", 6.67, "adm"),
  c("k-1-3", K, "K 1.3", "Caixas automáticas bancárias (ATM)", 16.67, "basico"),
  c("k-1-4", K, "K 1.4", "Terminais de pagamento de serviços (POS)", 20, "basico"),
  c("k-1-5", K, "K 1.5", "Máquinas electrónicas de contagem de dinheiro", 20, "basico"),
  c("k-1-6", K, "K 1.6", "Outras máquinas e equipamentos de uso específico", 20, "basico"),

  // === L — Saúde e acção social ===
  c("l-1-1", L, "L 1.1", "Edifícios destinados a serviços de saúde", 2.5, "edif"),
  c("l-1-2", L, "L 1.2", "Equipamentos, instrumentos e material médico-cirúrgico", 25, "basico"),
  c("l-1-3", L, "L 1.3", "Decorações interiores, incluindo tapeçarias", 20, "adm"),
  c("l-1-4", L, "L 1.4", "Máquinas de lavandaria, centrifugação e secagem", 12.5, "basico"),
  c("l-1-5", L, "L 1.5", "Equipamentos sanitários, cozinha e outros de uso específico", 14.28, "basico"),
  c("l-1-6", L, "L 1.6", "Mobiliário de quartos e enfermarias", 12.5, "adm"),
  c("l-1-7", L, "L 1.7", "Mobiliário de salas, salões e outras dependências", 10, "adm"),
  c("l-1-8", L, "L 1.8", "Colchoaria e cobertores", 20, "outr"),
  c("l-1-9", L, "L 1.9", "Roupas brancas e atoalhados", 50, "outr"),
  c("l-1-10", L, "L 1.10", "Louças e objectos de vidro (excepto decorativos)", 33.33, "outr"),
  c("l-1-11", L, "L 1.11", "Talheres e utensílios de cozinha", 25, "outr"),
  c("l-1-12", L, "L 1.12", "Outro material, aparelhos, utensílios e instalações de uso específico", 14.28, "basico"),
  c("l-1-13", L, "L 1.13", "Ambulâncias e seus apetrechos", 20, "trans"),

  // === M — Outras actividades de serviços colectivos ===
  c("m-1-1", M, "M 1.1", "Veículos de limpeza urbana e recolha de lixo", 20, "trans"),
  c("m-1-2", M, "M 1.2", "Contentores urbanos de lixo — metálicos", 20, "outr"),
  c("m-1-3", M, "M 1.3", "Contentores urbanos de lixo — plásticos", 25, "outr"),
  c("m-1-4", M, "M 1.4", "Compactadores, carregadores e lava-contentores", 14.28, "basico"),
  c("m-2-1", M, "M 2.1", "Rádio/TV — Instalações técnicas de radiodifusão e televisão", 16.66, "basico"),
  c("m-2-2", M, "M 2.2", "Rádio/TV — Instalações técnicas de radiocomunicação", 10, "basico"),
  c("m-2-3", M, "M 2.3", "Rádio/TV — Equipamento móvel de radiodifusão e televisão", 20, "basico"),
  c("m-2-4", M, "M 2.4", "Rádio/TV — Equipamento de sincronização e controlo", 14.28, "basico"),
  c("m-2-5", M, "M 2.5", "Rádio/TV — Equipamento de gravação e registo", 25, "basico"),
  c("m-2-6", M, "M 2.6", "Rádio/TV — Videocâmaras, videoprojectores, misturadores, digitalizadores", 25, "basico"),
  c("m-2-7", M, "M 2.7", "Rádio/TV — Retroprojectores, projectores, monitores, tradução simultânea", 20, "basico"),
  c("m-2-8", M, "M 2.8", "Rádio/TV — Tripés e equipamentos de iluminação", 16.66, "basico"),
  c("m-3-1", M, "M 3.1", "Recreativas — Cabines e salas de projecção, montagem, dobragem, revelação, cópia", 12.5, "edif"),
  c("m-3-2", M, "M 3.2", "Recreativas — Máquinas de som, projecção, montagem, dobragem, revelação e cópia", 14.28, "basico"),
  c("m-3-3", M, "M 3.3", "Recreativas — Máquinas e equipamentos de rodagem (câmaras, projectores, cabos)", 25, "basico"),
  c("m-3-4", M, "M 3.4", "Recreativas — Produções cinematográficas, fonográficas e de vídeo", 33.33, "outr"),
  c("m-3-5", M, "M 3.5", "Recreativas — Edifícios destinados exclusivamente a espectáculos", 4, "edif"),
  c("m-3-6", M, "M 3.6", "Recreativas — Decorações interiores, incluindo tapeçarias", 20, "adm"),
  c("m-3-7", M, "M 3.7", "Recreativas — Cortinas metálicas contra incêndio", 5, "basico"),
  c("m-3-8", M, "M 3.8", "Recreativas — Instalações desmontáveis", 20, "edif"),
  c("m-3-9", M, "M 3.9", "Recreativas — Máquinas recreativas e de jogos de azar", 20, "basico"),
  c("m-3-10", M, "M 3.10", "Recreativas — Outros equipamentos e aparelhos de uso específico", 12.5, "basico"),
  c("m-4-1-1", M, "M 4.1.1", "Lavandarias — Máquinas de lavagem, centrifugação e secagem", 12.5, "basico"),
  c("m-4-1-2", M, "M 4.1.2", "Lavandarias — Máquinas de limpeza a seco", 12.5, "basico"),
  c("m-4-1-3", M, "M 4.1.3", "Lavandarias — Outras máquinas e equipamentos de uso específico", 14.28, "basico"),
  c("m-4-2-1", M, "M 4.2.1", "Cabeleireiro/estética — Cadeiras articuladas e camas de massagens", 12.5, "basico"),
  c("m-4-2-2", M, "M 4.2.2", "Cabeleireiro/estética — Aparelhos para massagens, depilação, secagem", 14.28, "basico"),
  c("m-4-2-3", M, "M 4.2.3", "Cabeleireiro/estética — Instalações de uso específico", 10, "basico"),
  c("m-4-2-4", M, "M 4.2.4", "Cabeleireiro/estética — Roupas e fardas", 33.33, "outr"),
  c("m-4-2-5", M, "M 4.2.5", "Cabeleireiro/estética — Sinalização acústica/visual, sirenes, alarmes", 16.66, "basico"),
  c("m-4-2-6", M, "M 4.2.6", "Cabeleireiro/estética — Painéis indicadores (LCD, LED) publicitários", 20, "basico"),

  // === N — Activo incorpóreo ===
  c(
    "n-1",
    N,
    "N 1",
    "Despesas de investigação e desenvolvimento, incluindo elementos de propriedade industrial (patentes, marcas, alvarás, processos de fabrico)",
    20,
    "incorp",
    "incorporeo",
  ),
];

// Setores de Atividade Económica (CAE)
export const CAE_SECTIONS: { code: string; label: string }[] = [
  { code: "A", label: "A — Agricultura, produção animal, caça e silvicultura" },
  { code: "B", label: "B — Pesca" },
  { code: "C", label: "C — Indústrias extractivas" },
  { code: "D", label: "D — Indústrias transformadoras" },
  { code: "E", label: "E — Electricidade, gás e água" },
  { code: "F", label: "F — Construção" },
  { code: "G", label: "G — Comércio por grosso e a retalho" },
  { code: "H", label: "H — Alojamento e restauração" },
  { code: "I", label: "I — Transportes, armazenagem e comunicações" },
  { code: "J", label: "J — Actividades financeiras" },
  { code: "K", label: "K — Actividades imobiliárias, alugueres e serviços às empresas" },
  { code: "L", label: "L — Administração pública, defesa e segurança social" },
  { code: "M", label: "M — Educação" },
  { code: "N", label: "N — Saúde e acção social" },
  { code: "O", label: "O — Outras actividades de serviços colectivos" },
];

export function getCategory(id: string): DepreciationCategory | undefined {
  return DEPRECIATION_CATEGORIES.find((c) => c.id === id);
}
