/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransferenciasRouteImport } from './routes/transferencias'
import { Route as TabelaTaxasRouteImport } from './routes/tabela-taxas'
import { Route as InventarioRouteImport } from './routes/inventario'
import { Route as FiliaisRouteImport } from './routes/filiais'
import { Route as ClassesRouteImport } from './routes/classes'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AtivosNovoRouteImport } from './routes/ativos.novo'
import { Route as AtivosIdRouteImport } from './routes/ativos.$id'

const TransferenciasRoute = TransferenciasRouteImport.update({
  id: '/transferencias',
  path: '/transferencias',
  getParentRoute: () => rootRouteImport,
} as any)
const TabelaTaxasRoute = TabelaTaxasRouteImport.update({
  id: '/tabela-taxas',
  path: '/tabela-taxas',
  getParentRoute: () => rootRouteImport,
} as any)
const InventarioRoute = InventarioRouteImport.update({
  id: '/inventario',
  path: '/inventario',
  getParentRoute: () => rootRouteImport,
} as any)
const FiliaisRoute = FiliaisRouteImport.update({
  id: '/filiais',
  path: '/filiais',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassesRoute = ClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AtivosNovoRoute = AtivosNovoRouteImport.update({
  id: '/ativos/novo',
  path: '/ativos/novo',
  getParentRoute: () => rootRouteImport,
} as any)
const AtivosIdRoute = AtivosIdRouteImport.update({
  id: '/ativos/$id',
  path: '/ativos/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/classes': typeof ClassesRoute
  '/filiais': typeof FiliaisRoute
  '/inventario': typeof InventarioRoute
  '/tabela-taxas': typeof TabelaTaxasRoute
  '/transferencias': typeof TransferenciasRoute
  '/ativos/$id': typeof AtivosIdRoute
  '/ativos/novo': typeof AtivosNovoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/classes': typeof ClassesRoute
  '/filiais': typeof FiliaisRoute
  '/inventario': typeof InventarioRoute
  '/tabela-taxas': typeof TabelaTaxasRoute
  '/transferencias': typeof TransferenciasRoute
  '/ativos/$id': typeof AtivosIdRoute
  '/ativos/novo': typeof AtivosNovoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/classes': typeof ClassesRoute
  '/filiais': typeof FiliaisRoute
  '/inventario': typeof InventarioRoute
  '/tabela-taxas': typeof TabelaTaxasRoute
  '/transferencias': typeof TransferenciasRoute
  '/ativos/$id': typeof AtivosIdRoute
  '/ativos/novo': typeof AtivosNovoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/classes'
    | '/filiais'
    | '/inventario'
    | '/tabela-taxas'
    | '/transferencias'
    | '/ativos/$id'
    | '/ativos/novo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/classes'
    | '/filiais'
    | '/inventario'
    | '/tabela-taxas'
    | '/transferencias'
    | '/ativos/$id'
    | '/ativos/novo'
  id:
    | '__root__'
    | '/'
    | '/classes'
    | '/filiais'
    | '/inventario'
    | '/tabela-taxas'
    | '/transferencias'
    | '/ativos/$id'
    | '/ativos/novo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClassesRoute: typeof ClassesRoute
  FiliaisRoute: typeof FiliaisRoute
  InventarioRoute: typeof InventarioRoute
  TabelaTaxasRoute: typeof TabelaTaxasRoute
  TransferenciasRoute: typeof TransferenciasRoute
  AtivosIdRoute: typeof AtivosIdRoute
  AtivosNovoRoute: typeof AtivosNovoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transferencias': {
      id: '/transferencias'
      path: '/transferencias'
      fullPath: '/transferencias'
      preLoaderRoute: typeof TransferenciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tabela-taxas': {
      id: '/tabela-taxas'
      path: '/tabela-taxas'
      fullPath: '/tabela-taxas'
      preLoaderRoute: typeof TabelaTaxasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventario': {
      id: '/inventario'
      path: '/inventario'
      fullPath: '/inventario'
      preLoaderRoute: typeof InventarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/filiais': {
      id: '/filiais'
      path: '/filiais'
      fullPath: '/filiais'
      preLoaderRoute: typeof FiliaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classes': {
      id: '/classes'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof ClassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ativos/novo': {
      id: '/ativos/novo'
      path: '/ativos/novo'
      fullPath: '/ativos/novo'
      preLoaderRoute: typeof AtivosNovoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ativos/$id': {
      id: '/ativos/$id'
      path: '/ativos/$id'
      fullPath: '/ativos/$id'
      preLoaderRoute: typeof AtivosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClassesRoute: ClassesRoute,
  FiliaisRoute: FiliaisRoute,
  InventarioRoute: InventarioRoute,
  TabelaTaxasRoute: TabelaTaxasRoute,
  TransferenciasRoute: TransferenciasRoute,
  AtivosIdRoute: AtivosIdRoute,
  AtivosNovoRoute: AtivosNovoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
